version: "3.8"

services:
  rbac-db:
    image: postgres:17
    hostname: rbac-db
    container_name: rbac-db
    environment:
      - POSTGRES_USER=${RBAC_DB_USER}
      - POSTGRES_PASSWORD=${RBAC_DB_PASSWORD}
      - POSTGRES_DB=${RBAC_DB_DATABASE}
    volumes:
      - "rbac-db-data:/var/lib/postgresql/data"
    networks:
      internal:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${RBAC_DB_USER}"]
      interval: 10s
      start_period: 15s
      timeout: 10s
      retries: 3
    # network_mode: "host"

  rbac-backend:
    build:
      context: "${PWD}/rbac-server"
      dockerfile: Dockerfile
      args:
        PORT: ${RBAC_PORT}
    hostname: rbac-backend
    container_name: rbac-backend
    networks:
      internal:
        ipv4_address: ${RBAC_BACKEND_IP}
    depends_on:
      rbac-db:
        condition: service_healthy
    ports:
      - "5050:${RBAC_PORT}"
    environment:
      - RBAC_STORE_USER=${RBAC_DB_USER}
      - RBAC_STORE_PASSWORD=${RBAC_DB_PASSWORD}
      - RBAC_STORE_HOST=rbac-db
      - RBAC_STORE_PORT=5432
      - RBAC_STORE_DB=${RBAC_DB_DATABASE}
      - TRINO_GROUP_TXT_FILE_PATH=/opt/shared/groups.txt
    volumes:
      - "groups-data:/opt/shared"

  broadcast-channel:
    image: postgres:17
    hostname: broadcast-channel
    container_name: broadcast-channel
    environment:
      - POSTGRES_USER=${BROADCAST_CHANNEL_USER}
      - POSTGRES_PASSWORD=${BROADCAST_CHANNEL_PASSWORD}
      - POSTGRES_DB=${BROADCAST_CHANNEL_DATABASE}
    volumes:
      - "broadcast-channel-data:/var/lib/postgresql/data"
    networks:
      internal:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${BROADCAST_CHANNEL_USER}"]
      interval: 10s
      start_period: 15s
      timeout: 10s
      retries: 3

  opal-server:
    image: permitio/opal-server:0.8.3
    hostname: opal-server
    container_name: opal-server
    environment:
      - OPAL_BROADCAST_URI=${OPAL_BROADCAST_URI}
      - UVICORN_NUM_WORKERS=${UVICORN_NUM_WORKERS}
      - OPAL_POLICY_REPO_URL=${OPAL_POLICY_REPO_URL}
      - OPAL_POLICY_REPO_MAIN_BRANCH=${OPAL_POLICY_REPO_MAIN_BRANCH}
      - OPAL_POLICY_REPO_SSH_KEY=${OPAL_POLICY_REPO_SSH_KEY}
      - OPAL_POLICY_REPO_POLLING_INTERVAL=${OPAL_POLICY_REPO_POLLING_INTERVAL}
      - OPAL_DATA_CONFIG_SOURCES=${OPAL_DATA_CONFIG_SOURCES}
    ports:
      - "7002:7002"
    networks:
      internal:
        ipv4_address: ${OPAL_SERVER_IP}
    depends_on:
      broadcast-channel:
        condition: service_healthy

  opal-client-1:
    image: permitio/opal-client:0.8.3
    hostname: opal-client-1
    container_name: opal-client-1
    environment:
      - OPAL_SERVER_URL=${OPAL_SERVER_URL}
      - OPAL_DATA_TOPICS=${OPAL_DATA_TOPICS_1}
    ports:
      - "9001:7000"
      - "9081:8181"
    networks:
      internal:
      trino:
    depends_on:
      opal-server:
        condition: service_started

  opal-client-2:
    image: permitio/opal-client:0.8.3
    hostname: opal-client-2
    container_name: opal-client-2
    environment:
      - OPAL_SERVER_URL=${OPAL_SERVER_URL}
      - OPAL_DATA_TOPICS=${OPAL_DATA_TOPICS_2}
    ports:
      - "9002:7000"
      - "9082:8181"
    networks:
      internal:
      trino:
    depends_on:
      opal-server:
        condition: service_started

  trino-1:
    image: trinodb/trino:477
    hostname: trino-1
    container_name: trino-1
    ports:
      - "8081:8080"
    networks:
      trino:
    volumes:
      - "${PWD}/trino/opa-1.properties:/etc/trino/access-control.properties:ro"
      - "${PWD}/trino/group-provider.properties:/etc/trino/group-provider.properties:ro"
      - "${PWD}/trino/log.properties:/etc/trino/log.properties:ro"
      - "groups-data:/etc/trino-config:ro"

  trino-2:
    image: trinodb/trino:477
    hostname: trino-2
    container_name: trino-2
    ports:
      - "8082:8080"
    networks:
      trino:
    volumes:
      - "${PWD}/trino/opa-2.properties:/etc/trino/access-control.properties:ro"
      - "${PWD}/trino/group-provider.properties:/etc/trino/group-provider.properties:ro"
      - "${PWD}/trino/log.properties:/etc/trino/log.properties:ro"
      - "groups-data:/etc/trino-config:ro"

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: ${INTERNAL_SUBNET}
  trino:

volumes:
  broadcast-channel-data:
  rbac-db-data:
  groups-data:
